### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by aMySour** [kelpsyberry/dust#1]
What is the license of the project? Without a license, this project isn't technically open-source, just source-available.

**Comment by kelpsyberry** [comment]
I've been thinking about how to license the project, I can guarantee that it will be open-source and usable for all noncommercial uses at least! I still have to figure out how to handle commercial uses though, I think for now the most likely license is LGPL

**Comment by kelpsyberry** [comment]
I've thought about it more and I think I'll use GPLv3; LGPL is unenforceable for Rust projects due to the lack of dynamic linking and basically becomes equivalent to it, but I want to keep the requirement to publish any changes to the emulator so that any progress in accuracy or other things is shared.

**Comment by kelpsyberry** [comment]
Fixed in f791aa97fd0d2a070eb5c29b5dc98a50dbaf0b57!
