### ISSUE TITLE
how to fix "Unknown save type"?

### ISSUE THREAD

**Issue by Emil2010** [kelpsyberry/dust#8]
game: mario and luigi: bowser's inside story. OS: windows 11
i installed all bios and firmware, i set save folder, firmware is working, game is trying to find but fails
![dust-desktop_6faJhautOI](https://github.com/user-attachments/assets/d8cba2de-4c6b-4748-a446-43489f6051ea)

**Comment by Emil2010** [comment]
forgot to add: windows 11

**Comment by kelpsyberry** [comment]
In order to detect a game's save file type without an existing save file you need to download [game_db.json](https://github.com/kelpsyberry/dust/blob/main/game_db.json) from this repository and set the game database path in the configuration window (Paths > Game database) to the path you stored it at. Sorry for not documenting it further, it should be fixed and streamlined in the future.
